from frmMain import CfrmMain
from frmSplash import CfrmSplash
from frmAbout import CfrmAbout
from tbToolBox import CtbToolBox
from frmProperties import CfrmProperties
from frmOpen import CfrmOpen
from frmSave import CfrmSave
from frmFindInDiagram import CFindInDiagram
from frmOptions import CfrmOptions
from frmException import CfrmException
