from DomainAttributeModification import CDomainAttributeModification
from DeleteAttributeModification import CDeleteAttributeModification
from ReplaceAttributeModification import CReplaceAttributeModification